# Generated by Django 5.2.11 on 2026-09-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_professionalprofile_service_cities"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalprofile",
            name="stripe_connect_account_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="stripe_connect_account_type",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="stripe_connect_charges_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="stripe_connect_payouts_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
