# Generated by Django 5.2.11 on 2026-09-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_professionalprofile_stripe_connect_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="professionalprofile",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
