# Generated by Django 6.1 on 2026-08-16 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='accounts.professionalprofile')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('INSTANT', 'Instant'), ('SCHEDULED', 'Scheduled')], max_length=20)),
                ('status', models.CharField(choices=[('SEARCHING', 'Searching for a professional'), ('PENDING_ACCEPT', 'Awaiting professional response'), ('CONFIRMED', 'Confirmed'), ('AWAITING_REAFFIRMATION', 'Awaiting 1-hour reaffirmation'), ('LEFT', 'Professional left'), ('REACHED', 'Professional reached (GPS-verified)'), ('STARTED', 'Work started'), ('COMPLETED', 'Work completed — pending customer confirmation'), ('CONFIRMED_COMPLETE', 'Customer confirmed completion'), ('CANCELLED_CUSTOMER', 'Cancelled by customer'), ('CANCELLED_PROFESSIONAL', 'Cancelled by professional'), ('NO_MATCH', 'No professional found in service area')], default='SEARCHING', max_length=30)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('travel_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('priority_fee', models.DecimalField(decimal_places=2, default=0, help_text='Fixed charge added for Instant bookings only (Section 9).', max_digits=8)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='Set for SCHEDULED bookings only.', null=True)),
                ('reaffirmation_confirmed_by_customer', models.BooleanField(default=False)),
                ('reaffirmation_confirmed_by_professional', models.BooleanField(default=False)),
                ('reached_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('reached_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('before_after_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('reached_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_complete_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_customer', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(blank=True, help_text='Null while SEARCHING (instant) or before acceptance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_professional', to='accounts.professionalprofile')),
                ('professional_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.professionalservice')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDecline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('declined_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declines', to='bookings.booking')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BookingStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SEARCHING', 'Searching for a professional'), ('PENDING_ACCEPT', 'Awaiting professional response'), ('CONFIRMED', 'Confirmed'), ('AWAITING_REAFFIRMATION', 'Awaiting 1-hour reaffirmation'), ('LEFT', 'Professional left'), ('REACHED', 'Professional reached (GPS-verified)'), ('STARTED', 'Work started'), ('COMPLETED', 'Work completed — pending customer confirmation'), ('CONFIRMED_COMPLETE', 'Customer confirmed completion'), ('CANCELLED_CUSTOMER', 'Cancelled by customer'), ('CANCELLED_PROFESSIONAL', 'Cancelled by professional'), ('NO_MATCH', 'No professional found in service area')], max_length=30)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='bookings.booking')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
    ]
