# Generated by Django 6.1 on 2026-08-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="availability_slot",
            field=models.ForeignKey(
                blank=True,
                help_text="Reserved slot for scheduled bookings.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="bookings.availabilityslot",
            ),
        ),
    ]
