# Generated by Django 5.2.11 on 2026-09-05 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_availability_slot"),
        ("catalog", "0002_marketplacesettings_service_duration_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.CreateModel(
            name="BookingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duration_minutes", models.PositiveSmallIntegerField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_services",
                        to="bookings.booking",
                    ),
                ),
                (
                    "professional_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.professionalservice",
                    ),
                ),
            ],
            options={
                "unique_together": {("booking", "professional_service")},
            },
        ),
    ]
