# Generated by Django 5.2.11 on 2026-09-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_bookingnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilityslot",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookingnotification",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
