# Generated by Django 5.2.11 on 2026-09-05 01:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instant_initial_radius_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "instant_max_radius_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=25,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "scheduled_search_radius_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=25,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "radius_expansion_step_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "professional_service_radius_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=25,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "maximum_travel_distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=25,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "included_travel_distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "travel_fee_per_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "maximum_travel_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "minimum_booking_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "fixed_platform_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "customer_cancellation_window_minutes",
                    models.PositiveIntegerField(default=60),
                ),
                (
                    "professional_acceptance_window_minutes",
                    models.PositiveIntegerField(default=10),
                ),
                (
                    "scheduled_minimum_notice_minutes",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "maximum_advance_booking_days",
                    models.PositiveIntegerField(default=365),
                ),
                (
                    "instant_booking_timeout_minutes",
                    models.PositiveIntegerField(default=10),
                ),
                ("rematching_enabled", models.BooleanField(default=True)),
                ("instant_booking_enabled", models.BooleanField(default=True)),
                ("scheduled_booking_enabled", models.BooleanField(default=True)),
                ("multiple_service_booking_enabled", models.BooleanField(default=True)),
                ("travel_fees_enabled", models.BooleanField(default=True)),
                ("availability_weight", models.PositiveIntegerField(default=100)),
                ("distance_weight", models.PositiveIntegerField(default=50)),
                ("rating_weight", models.PositiveIntegerField(default=20)),
                ("review_count_weight", models.PositiveIntegerField(default=10)),
                ("experience_weight", models.PositiveIntegerField(default=5)),
                ("reliability_weight", models.PositiveIntegerField(default=5)),
                ("tax_enabled", models.BooleanField(default=False)),
                ("tax_name", models.CharField(blank=True, max_length=100)),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Marketplace settings",
                "verbose_name_plural": "Marketplace settings",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(
                default=60,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(480),
                ],
            ),
        ),
        migrations.CreateModel(
            name="MarketplaceSettingsAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changes", models.JSONField(default=dict)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_entries",
                        to="catalog.marketplacesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
