# Generated by Django 5.2.11 on 2026-09-05 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_marketplacesettings_service_duration_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplacesettings",
            name="maximum_platform_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="marketplacesettings",
            name="minimum_platform_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="marketplacesettings",
            name="rematching_timeout_minutes",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="marketplacesettings",
            name="reminder_minutes_before_booking",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
