# Generated by Django 5.2.11 on 2026-09-07 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_marketplacesettings_maximum_platform_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="professionalservice",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="default_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="service",
            name="display_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="parent_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                to="catalog.service",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="audience",
            field=models.CharField(
                choices=[
                    ("MEN", "Men"),
                    ("WOMEN", "Women"),
                    ("KIDS", "Kids"),
                    ("UNISEX", "Unisex"),
                ],
                default="UNISEX",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="display_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
