# Generated by Django 5.2.11 on 2026-09-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_category_is_demo_professionalservice_is_demo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplacesettingsaudit",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
