# Generated by Django 6.1 on 2026-08-16 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('CERTN', 'Certn'), ('PERSONA', 'Persona')], max_length=20)),
                ('provider_reference_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired — re-verification required')], default='PENDING', max_length=20)),
                ('fee_paid', models.BooleanField(default=False, help_text='Submission is only sent to the provider once this is True (Section 11, step 2).')),
                ('identity_check_passed', models.BooleanField(blank=True, null=True)),
                ('criminal_record_check_passed', models.BooleanField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Annual re-verification per Section 11, step 6.', null=True)),
                ('decided_by', models.ForeignKey(blank=True, help_text='Admin who approved/rejected in the dashboard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_decisions', to=settings.AUTH_USER_MODEL)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='accounts.professionalprofile')),
            ],
        ),
    ]
