# Generated by Django 5.2.11 on 2026-09-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalverification",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
