# Generated by Django 6.1 on 2026-08-16 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized (held)'), ('CAPTURED', 'Captured'), ('CANCELLED', 'Authorization cancelled (no charge)'), ('REFUNDED', 'Refunded after capture')], default='AUTHORIZED', max_length=20)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.CharField(blank=True, help_text='Set when admin adjusts/refunds from the dashboard.', max_length=255)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_authorization', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255)),
                ('dispute_window_ends_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='bookings.booking')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='accounts.professionalprofile')),
            ],
        ),
    ]
