# Generated by Django 5.2.11 on 2026-08-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentauthorization",
            name="status",
            field=models.CharField(
                choices=[
                    ("AUTHORIZED", "Authorized (held)"),
                    ("CAPTURED", "Captured"),
                    ("CANCELLED", "Authorization cancelled (no charge)"),
                    ("REFUNDED", "Refunded after capture"),
                    ("FAILED", "Payment failed"),
                ],
                default="AUTHORIZED",
                max_length=20,
            ),
        ),
    ]
