# Generated by Django 5.2.11 on 2026-09-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_paymentauthorization_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="paymentauthorization",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Payment method confirmation pending"),
                    ("AUTHORIZED", "Authorized (held)"),
                    ("CAPTURED", "Captured"),
                    ("CANCELLED", "Authorization cancelled (no charge)"),
                    ("REFUNDED", "Refunded after capture"),
                    ("FAILED", "Payment failed"),
                ],
                default="AUTHORIZED",
                max_length=20,
            ),
        ),
    ]
