# Generated by Django 5.2.11 on 2026-09-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_stripeevent_alter_paymentauthorization_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="provider_error",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="payout",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending provider transfer"),
                    ("PROCESSING", "Transfer processing"),
                    ("PAID", "Paid"),
                    ("FAILED", "Transfer failed"),
                    ("REVERSED", "Transfer reversed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
