# Generated by Django 5.2.11 on 2026-09-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payout_provider_error_payout_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentauthorization",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentauthorization",
            name="provider",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("demo", "Demo")],
                default="stripe",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
